--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: fetchcurrencyms
    version: v1
  name: fetchcurrencyms
spec: 
  ports: 
    - 
      name: http
      port: 9095
      targetPort: 9095
  selector: 
    app: fetchcurrencyms
    version: v1
  type: NodePort