spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devzenith/BangaloreApril2020ConfigGit.git
    bus:
      destination: configXchange
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.100}   
    port: 5672   
server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
            
